name: Windows test

on:
  push:
  #   branches: master
  # pull_request:
  #   branches: '*'
  # workflow_dispatch:
  #   branches: '*'

env:
  LUAROCKS_DEPS_DIR: c:\external
  LUAROCKS_DEPS_OPENSSL_VER: "3.4.1"
  LUAROCKS_DEPS_ZLIB_VER: "1.3.1"
  LUAROCKS_WINDOWS_GH_CI: "ci-windows"

jobs:
  ##############################################################################
  ci-windows-build-test:
    runs-on: "windows-latest"
    defaults:
      run:
        shell: cmd
    strategy:
      fail-fast: false
      matrix:
        include:
          #
          # Visual Studio x64
          #

          # quick tests
          - LUAV: "2.1"
            LUAT: "luajit"
            COMPILER: "vs"
            FILES: ""
            EXCLUDE: "integration,unit"
            TESTTYPE: ""
            TESTID: "001"
            ARCH: x64
          # Lua 5.4 tests
          - LUAV: "5.4"
            LUAT: "lua"
            COMPILER: "vs"
            FILES: ""
            EXCLUDE: "integration,quick"
            TESTTYPE: "unit"
            TESTID: "002"
            ARCH: x64
          # - LUAV: "5.4"
          #   LUAT: "lua"
          #   COMPILER: "vs"
          #   FILES: ""
          #   EXCLUDE: "unit,quick"
          #   TESTTYPE: ""
          #   TESTID: "003"
          #   ARCH: x64
          # - LUAV: "5.4"
          #   LUAT: "lua"
          #   COMPILER: "vs"
          #   FILES: "spec//build_spec.lua"
          #   EXCLUDE: ""
          #   TESTTYPE: ""
          #   TESTID: "004"
          #   ARCH: x64
          # # LuaJIT 2.1 tests
          # - LUAV: "2.1"
          #   LUAT: "luajit"
          #   COMPILER: "vs"
          #   FILES: ""
          #   EXCLUDE: "integration,quick"
          #   TESTTYPE: "unit"
          #   TESTID: "005"
          #   ARCH: x64
          # - LUAV: "2.1"
          #   LUAT: "luajit"
          #   COMPILER: "vs"
          #   FILES: ""
          #   EXCLUDE: "unit,quick"
          #   TESTTYPE: ""
          #   TESTID: "006"
          #   ARCH: x64
          # - LUAV: "2.1"
          #   LUAT: "luajit"
          #   COMPILER: "vs"
          #   FILES: "spec//build_spec.lua"
          #   EXCLUDE: ""
          #   TESTTYPE: ""
          #   TESTID: "007"
          #   ARCH: x64

          # #
          # # MinGW-w64 with Universal C Run Time
          # # provided by MSYS2
          # #

          # # quick tests
          # - LUAV: "2.1"
          #   LUAT: "luajit"
          #   COMPILER: "mingw"
          #   FILES: ""
          #   EXCLUDE: "integration,unit"
          #   TESTTYPE: ""
          #   TESTID: "008"
          # # Lua 5.4 tests
          # - LUAV: "5.4"
          #   LUAT: "lua"
          #   COMPILER: "mingw"
          #   FILES: ""
          #   EXCLUDE: "integration,quick"
          #   TESTTYPE: "unit"
          #   TESTID: "009"
          # - LUAV: "5.4"
          #   LUAT: "lua"
          #   COMPILER: "mingw"
          #   FILES: ""
          #   EXCLUDE: "unit,quick"
          #   TESTTYPE: ""
          #   TESTID: "010"
          # - LUAV: "5.4"
          #   LUAT: "lua"
          #   COMPILER: "mingw"
          #   FILES: "spec//build_spec.lua"
          #   EXCLUDE: ""
          #   TESTTYPE: ""
          #   TESTID: "011"
          # # LuaJIT 2.1 tests
          # - LUAV: "2.1"
          #   LUAT: "luajit"
          #   COMPILER: "mingw"
          #   FILES: ""
          #   EXCLUDE: "integration,quick"
          #   TESTTYPE: "unit"
          #   TESTID: "012"
          # - LUAV: "2.1"
          #   LUAT: "luajit"
          #   COMPILER: "mingw"
          #   FILES: ""
          #   EXCLUDE: "unit,quick"
          #   TESTTYPE: ""
          #   TESTID: "013"
          # - LUAV: "2.1"
          #   LUAT: "luajit"
          #   COMPILER: "mingw"
          #   FILES: "spec//build_spec.lua"
          #   EXCLUDE: ""
          #   TESTTYPE: ""
          #   TESTID: "014"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSVC dev prompt
        if: ${{ matrix.COMPILER == 'vs' }}
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.ARCH }}

      - name: Add bin directory of dependencies to system PATH environment variable
        run: echo ${{ env.LUAROCKS_DEPS_DIR }}\bin>>${{ github.path }}
        
      - name: Cache zlib tarball
        if: ${{ matrix.COMPILER == 'vs' }}
        id: cache-zlib-tarball
        uses: actions/cache@v4
        with:
          path: zlib-${{ env.LUAROCKS_DEPS_ZLIB_VER }}.tar.gz
          key: zlib-${{ env.LUAROCKS_DEPS_ZLIB_VER }}

      - name: Install dependency (zlib)
        if: ${{ matrix.COMPILER == 'vs' }}
        run: |
          cd "${{ runner.temp }}" && mkdir zlib && cd zlib;

          IF NOT "${{ steps.cache-zlib-tarball.outputs.cache-hit }}"=="true" (
            curl "-o" "${{ github.workspace }}\zlib-${{ env.LUAROCKS_DEPS_ZLIB_VER }}.tar.gz" ^
              "https://zlib.net/zlib-${{ env.LUAROCKS_DEPS_ZLIB_VER }}.tar.gz"
          )
          
          tar -xf "${{ github.workspace }}\zlib-${{ env.LUAROCKS_DEPS_ZLIB_VER }}.tar.gz"
          
          IF "${{ matrix.COMPILER }}"=="vs" (
            SET CMAKE_GENERATOR=NMake Makefiles
            SET CC=cl
          ) ELSE (
            SET CMAKE_GENERATOR=MinGW Makefiles
            SET CC=gcc
          )
          
          cmake "-G" "%CMAKE_GENERATOR%" ^
            "-DCMAKE_C_COMPILER=%CC%" ^
            "-DCMAKE_BUILD_TYPE=Release" ^
            "-DBUILD_SHARED_LIBS=ON" ^
            "-DBUILD_STATIC_LIBS=OFF" ^
            "--install-prefix" "${{ env.LUAROCKS_DEPS_DIR }}" ^
            "-S" "zlib-${{ env.LUAROCKS_DEPS_ZLIB_VER }}" ^
            "-B" "_build-zlib" && ^
          cmake "--build" "_build-zlib" "--config" "Release" && ^
          cmake "--install" "_build-zlib" "--config" "Release"

          IF "${{ matrix.COMPILER }}"=="vs" (
            copy "${{ env.LUAROCKS_DEPS_DIR }}\lib\zlib.lib" ^
              "${{ env.LUAROCKS_DEPS_DIR }}\lib\z.lib"
          )
      
      - name: Install dependency (libbz2)
        if: ${{ matrix.COMPILER == 'vs' }}
        run: |
          cd "${{ runner.temp }}" && ^
          git clone https://gitlab.com/bzip2/bzip2
          
          IF "${{ matrix.COMPILER }}"=="vs" (
            SET CMAKE_GENERATOR=NMake Makefiles
            SET CC=cl
          ) ELSE (
            SET CMAKE_GENERATOR=MinGW Makefiles
            SET CC=gcc
          )
          
          cmake "-G" "%CMAKE_GENERATOR%" ^
            "-DCMAKE_C_COMPILER=%CC%" ^
            "-DCMAKE_BUILD_TYPE=Release" ^
            "-DENABLE_SHARED_LIB=ON" ^
            "-DENABLE_LIB_ONLY=ON" ^
            "--install-prefix" "${{ env.LUAROCKS_DEPS_DIR }}" ^
            "-S" "bzip2" ^
            "-B" "_build-bz2" && ^
          cmake "--build" "_build-bz2" "--config" "Release" && ^
          cmake "--install" "_build-bz2" "--config" "Release"

          IF EXIST "${{ env.LUAROCKS_DEPS_DIR }}\lib\bz2.dll" (
            COPY /Y "${{ env.LUAROCKS_DEPS_DIR }}\lib\bz2.dll" ^
              "${{ env.LUAROCKS_DEPS_DIR }}\bin"
          )
      
      - name: Cache OpenSSL installer
        if: ${{ matrix.COMPILER == 'vs' }}
        id: cache-openssl-installer
        uses: actions/cache@v4
        with:
          path: build\openssl-installer-${{ env.LUAROCKS_DEPS_OPENSSL_VER }}-${{ matrix.ARCH }}.exe
          key: openssl-${{ env.LUAROCKS_DEPS_OPENSSL_VER }}-${{ matrix.ARCH }}
      
      - name: Instal dependency (OpenSSL)
        if: ${{ matrix.COMPILER == 'vs' }}
        shell: pwsh
        # On Windows, building OpenSSL from source code is quite slow (20m ~ 30m).
        # In order to get pre-built binaries (CI purposes) for the OpenSSL library
        # ABI-compatible with MSVC, a faster approach can be achieved
        # by downloading the binaries from a known third-party.

        # slproweb ( https://slproweb.com/products/Win32OpenSSL.html ) is a long
        # time third-party providing pre-built OpenSSL binaries through
        # Windows installers.

        # Below, we follow the idea contained at
        # https://github.com/actions/runner-images/blob/a88fc4db06ae2350cb3128627b7fe4b5ee847f8e/images/windows/scripts/build/Install-OpenSSL.ps1
        # to install OpenSSL from slproweb.

        # Note: AppVeyor pre-built binaries for OpenSSL
        #         come from this provider.
        run: |
          $installerName = "${{ github.workspace }}\build\openssl-installer-${{ env.LUAROCKS_DEPS_OPENSSL_VER }}-${{ matrix.ARCH }}.exe";

          if ("${{ steps.cache-openssl-installer.outputs.cache-hit }}" -ne "true")
          {
            $arch = 'INTEL';
            
            if ("${{ matrix.ARCH }}" -eq "x86") { $bits = '32'; }
            elseif ("${{ matrix.ARCH }}" -eq "x64") { $bits = '64'; }
            else { $bits = '-1'; }

            $light = $false;
            $version = "${{ env.LUAROCKS_DEPS_OPENSSL_VER }}";

            # Fetch available installers list
            $jsonUrl = 'https://raw.githubusercontent.com/slproweb/opensslhashes/master/win32_openssl_hashes.json';

            $installersAvailable = (Invoke-RestMethod $jsonUrl).files;
            $installerNames = $installersAvailable | Get-Member -MemberType NoteProperty | Select-Object -ExpandProperty Name;

            $installerUrl = $null;
            $installerHash = $null;

            foreach ($key in $installerNames) {
              $installer = $installersAvailable.$key;
              if (($installer.light -eq $light) -and ($installer.arch -eq $arch) -and ($installer.bits -eq $bits) -and ($installer.installer -eq "exe") -and ($installer.basever -eq $version)) {
                $installerUrl = $installer.url;
                $installerHash = $installer.sha512.Replace("-", "").ToLower();
                break;
              }
            }

            if ($installerUrl -eq $null) {
              throw "Installer not found for version $version";
            }

            # Download the installer
            curl "--create-dirs" "-o" "${installerName}" "${installerUrl}";

            # Validate sha512 checksum
            $downloadedHash = Get-FileHash -Path "${installerName}" -Algorithm "SHA512" |
              Select-Object -ExpandProperty Hash;
            
            $downloadedHash = $downloadedHash.Replace("-", "").ToLower();

            if ("${downloadedHash}" -ne "${installerHash}")
            {
              throw "Installer SHA512 hash mismatch: (Expected ${installerHash}), (Got ${downloadedHash})";
            }
          }
          
          Start-Process `
            -FilePath "${installerName}" `
            -ArgumentList "/verysilent", "/sp-", "/suppressmsgboxes", "/DIR=`"${{ env.LUAROCKS_DEPS_DIR }}`"" `
            -Wait;
          
          $deps_lib_dir = Join-Path -Path "${{ env.LUAROCKS_DEPS_DIR }}" -ChildPath "lib";
          if (Test-Path -Path $deps_lib_dir)
          {
            foreach ($imp_lib in "libssl.lib", "libcrypto.lib")
            {
              $current_imp_lib = Join-Path -Path "${deps_lib_dir}" -ChildPath "${imp_lib}";
              if (-not (Test-Path -Path $current_imp_lib))
              {
                $current_imp_lib = Get-ChildItem -Path $deps_lib_dir -Recurse -File |
                  Where-Object Name -EQ "${imp_lib}" |
                  Select-Object -ExpandProperty FullName -First 1;
                
                Copy-Item -Path $current_imp_lib -Destination $deps_lib_dir;
              }
            }
          }
      
      - name: Setup mingw-w64 and dependencies (UCRT64)
        if: ${{ matrix.COMPILER == 'mingw' }}
        run: |
          SET PKGS_TO_INSTALL=mingw-w64-ucrt-x86_64-cc ^
            mingw-w64-ucrt-x86_64-make ^
            mingw-w64-ucrt-x86_64-zlib ^
            mingw-w64-ucrt-x86_64-bzip2 ^
            mingw-w64-ucrt-x86_64-openssl

          C:\msys64\usr\bin\bash "-lc" ^
            "pacman -S %PKGS_TO_INSTALL% --noconfirm"
          
          echo C:\msys64\ucrt64\bin>>${{ github.path }}
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          # employ the latest Python version
          # described at https://pypi.org/project/hererocks/
          python-version: '3.11'
      
      - name: Install SSL certificate
        run: |
          pip install --upgrade certifi
          FOR /F "tokens=* USEBACKQ" %%F IN (`python -c "import certifi;print(certifi.where())"`) DO (
            echo SSL_CERT_FILE=%%F>>${{ github.env }}
          )
      
      - name: Checkout a pinned version of LuaRocks
        uses: actions/checkout@v4
        with:
          ref: 6e4e43356d5bfac748b4457f9dad4b0757fee85b
          path: build/pinned-luarocks
      
      - name: Install ${{ matrix.LUAT }} ${{ matrix.LUAV }}
        run: |
          SET "CURRENT_LUA_DIRNAME=lua_install-${{ matrix.LUAV }}"
          SET "CURRENT_LUA_DIR=${{ github.workspace }}\%CURRENT_LUA_DIRNAME%"
          SET "CURRENT_LUA_BIN=%CURRENT_LUA_DIR%\bin"
          SET "CURRENT_LUA_INTERPRETER=%CURRENT_LUA_BIN%\lua.exe"
          SET "LR_PREFIX=${{ runner.temp }}\luarocks"
          SET "LR_CONFIG=%LR_PREFIX%\conf"

          pip install hererocks && ^
          hererocks ^
            "%CURRENT_LUA_DIRNAME%" ^
            "--${{ matrix.LUAT }}" ^
            "${{ matrix.LUAV }}" ^
            "--luarocks" "latest" ^
            "--target=${{ matrix.COMPILER }}" && ^
          rmdir /S /Q %CURRENT_LUA_DIR%\luarocks && ^
          rmdir /S /Q %APPDATA%\luarocks && ^
          del /Q %CURRENT_LUA_BIN%\luarocks*
          
          IF "${{ matrix.COMPILER }}"=="vs" (
            SET TGT=MSVC
          ) ELSE (
            SET TGT=MW
          )

          cd build\pinned-luarocks && ^
          call "install.bat" ^
            "/P" "%LR_PREFIX%" ^
            "/CONFIG" "%LR_CONFIG%" ^
            "/LUA" "%CURRENT_LUA_DIR%" ^
            "/%TGT%" ^
            "/Q" "/NOREG"

          IF NOT "%ERRORLEVEL%"=="0" EXIT /B 1

          echo %CURRENT_LUA_BIN%>>${{ github.path }}
          echo %LR_PREFIX%>>${{ github.path }}
          echo CURRENT_LUA_DIR=%CURRENT_LUA_DIR%>>${{ github.env }}
          echo CURRENT_LUA_BIN=%CURRENT_LUA_BIN%>>${{ github.env }}
          echo CURRENT_LUA_INTERPRETER=%CURRENT_LUA_INTERPRETER%>>${{ github.env }}
          echo BUSTED_BAT=%LR_PREFIX%\busted.bat>>${{ github.env }}
          echo LUACOV_BAT=%LR_PREFIX%\luacov.bat>>${{ github.env }}

      - name: Configure MSVCRT to build dependencies
        if: ${{ matrix.COMPILER == 'mingw' }}
        run: |
          SET MSVCRT_LUA_CODE=local pe = require [[win32.pe-parser]]; ^
            local rt, _ = pe.msvcrt [[${{ env.CURRENT_LUA_INTERPRETER }}]]; ^
            print(rt or 'nil')
          
          FOR /F "tokens=* USEBACKQ" %%I IN (`lua -e "%MSVCRT_LUA_CODE%"`) DO (
            IF NOT "%%I"=="nil" (
              luarocks config variables.MSVCRT "%%I"
            )
          )
      
      - name: Cache rocks
        uses: actions/cache@v4
        with:
          path: |
            **/*.src.rock
          key: rocks

      - name: Install compat53
        run: luarocks install compat53
        
      - name: Install busted
        run: IF NOT EXIST "${{ env.BUSTED_BAT }}" luarocks install busted
      
      - name: Install cluacov
        run: IF NOT EXIST "${{ env.LUACOV_BAT }}" luarocks install cluacov
        
      - name: Install busted-htest
        run: luarocks install busted-htest
      
      - name: Run test
        run: |
          busted ^
            "-o" "htest" ^
            "-v" "--lpath=.//?.lua" ^
            "--exclude-tags=ssh,unix,${{ matrix.EXCLUDE }}" ^
            "-Xhelper" ^
            "lua_dir=${{ env.CURRENT_LUA_DIR }},${{ env.LUAROCKS_WINDOWS_GH_CI }},${{ matrix.COMPILER }}" ^
            ${{ matrix.FILES }}
      
      - name: Run unit test
        if: ${{ matrix.TESTTYPE == 'unit' }}
        run: |
          busted ^
            "-o" "htest" ^
            "-v" "--lpath=.//?.lua" ^
            "--exclude-tags=ssh,unix,${{ matrix.EXCLUDE }}" ^
            "-Xhelper" ^
            "lua_dir=${{ env.CURRENT_LUA_DIR }},${{ env.LUAROCKS_WINDOWS_GH_CI }},${{ matrix.COMPILER }},env=full" ^
            ${{ matrix.FILES }}
      
      - name: Generate code coverage report
        run: |
          luacov "-c" "testrun/luacov.config" && ^
          copy "testrun/luacov.report.out" "luacov.report-${{ matrix.TESTID }}.out"

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: luacov.report-${{ matrix.TESTID }}.out
          path: luacov.report-${{ matrix.TESTID }}.out

  ci-windows:
    runs-on: windows-latest
    needs: ci-windows-build-test
    steps:

      - name: Download coverage reports
        uses: actions/download-artifact@v4
      
      # - name: Upload code coverage
      #   uses: codecov/codecov-action@v5
      #   with:
      #     disable_search: true
      #     files: luacov.report-001.out,luacov.report-002.out,luacov.report-003.out,luacov.report-004.out,luacov.report-005.out,luacov.report-006.out,luacov.report-007.out,luacov.report-008.out,luacov.report-009.out,luacov.report-010.out,luacov.report-011.out,luacov.report-012.out,luacov.report-013.out,luacov.report-014.out
      #     token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload code coverage
        uses: codecov/codecov-action@v5
        with:
          disable_search: true
          files: luacov.report-001.out,luacov.report-002.out
          token: ${{ secrets.CODECOV_TOKEN }}